# Generated by Django 2.2.1 on 2019-05-22 18:37

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Fakturowania'), (2, 'Dostawy'), (3, 'Siedziba')], max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('number', models.PositiveSmallIntegerField(blank=True)),
                ('number_room', models.CharField(blank=True, max_length=10)),
                ('postal_code', models.PositiveSmallIntegerField(blank=True)),
                ('city', models.CharField(max_length=40)),
                ('tax_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Nazwa firmy')),
                ('description', models.CharField(max_length=1000, verbose_name='Opis firmy')),
            ],
        ),
    ]
