# Generated by Django 2.2.1 on 2019-05-22 18:59

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seller.Seller'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Fakturowania'), (2, 'Dostawy'), (3, 'Siedziba')], max_length=3),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
