# Generated by Django 2.2.1 on 2019-05-20 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_name_father', models.ForeignKey(blank=True, default='EMPTY', on_delete=django.db.models.deletion.SET_DEFAULT, to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=4000)),
                ('price', models.FloatField()),
                ('product_category', models.ForeignKey(default='EMPTY', on_delete=django.db.models.deletion.SET_DEFAULT, to='products.Category')),
            ],
        ),
    ]
