# Generated by Django 2.2.1 on 2019-05-20 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name_father',
            field=models.ForeignKey(blank=True, default='empty', on_delete=django.db.models.deletion.SET_DEFAULT, to='products.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, default='EMPTY', on_delete=django.db.models.deletion.SET_DEFAULT, to='products.Category'),
        ),
    ]
