# Generated by Django 2.2.1 on 2019-05-20 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190521_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name_father',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Category'),
        ),
    ]
