# Generated by Django 2.2.1 on 2019-05-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190521_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='number',
        ),
    ]
